work_dir: ./work_dir/test_run

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  # data_path: data/ntu/NTU60_CS.npz
  data_path: /kaggle/input/ntu60-processed-skeleton-dataset/ntu60/NTU60_CS.npz
  split: train
  debug: True  # Use only first 100 samples for quick test
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: False  # Disable for faster testing
  p_interval: [1.0]  # No augmentation for faster testing
  vel: False
  bone: False

test_feeder_args:
  # data_path: data/ntu/NTU60_CS.npz
  data_path: /kaggle/input/ntu60-processed-skeleton-dataset/ntu60/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [1.0]
  vel: False
  bone: False
  debug: True  # Use only first 100 samples for quick test

# model
model: model.ctrgcn.Model_lst_4part
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  k: 8
  head: ['ViT-B/32']
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.1
lr_decay_rate: 0.1
step: [2, 3]  # Early steps for 3 epoch test
warm_up_epoch: 0

# training
device: [0]
batch_size: 8  # Small batch for quick test
test_batch_size: 8
num_epoch: 3  # Just 3 epochs for quick test
nesterov: True

